### ISSUE TITLE
Enhancement: support context cancellation

### ISSUE THREAD

**Issue by thomascoquet** [airbusgeo/godal#57]
Hello Thomas,

When used within a tile server, it happens often that tile requests get canceled by OpenLayers or Leaflet when the user pans/zooms faster than the server throughput. godal does not support context cancellation, what can waste (a lot of) resources in such cases. Cancelling early could be quite beneficial.

Obviously, one cannot cancel a cgo call from the go runtime and I expect an implementation in C++ to be complex.
However, one could still cancel early at the io level (in `osio`), resulting in resource savings.

I did a dumb example at the Adapter level. Basically, the idea is to combine the key with a context id, to register the context in a global map and to fetch it when doing io in `osio`.

```go
var mutex sync.Mutex
var contexts map[string]context.Context

func unwrapkey(key string) string {
	last := strings.LastIndex(key, "#")
	if last != -1 {
		key = key[:last]
	}
	return key
}

func WithContext(ctx context.Context, key string) string {
	mutex.Lock()
	defer mutex.Unlock()

	cid := uuid.New().String()
	contexts[cid] = ctx
	return fmt.Sprintf("%s#%s", key, cid)
}

func GetContext(key string) (context.Context, string) {
	mutex.Lock()
	defer mutex.Unlock()

	last := strings.LastIndex(key, "#")
	if last == -1 {
		return context.Background(), key
	}
	ctx, ok := contexts[key[last+1:]]
	if !ok {
		ctx = context.Background()
	}
	key = key[:last]
	return ctx, key
}

func init() {
	contexts = map[string]context.Context{}
	// todo: launch goroutine and clean done contexts
}
```

```go
type KeyStreamerAt interface {
	StreamAt(ctx context.Context, key string, off int64, n int64) (io.ReadCloser, int64, error)
}
```

```go
func (a *Adapter) srcStreamAt(key string, off int64, n int64) (io.ReadCloser, error) {
	ctx, key := GetContext(key)
        ...
}
```

As simple as it may be, it works well enough. We could imagine `WarpWithContext(ctx, ...)`, etc.
Hope all of this makes sense.
Thomas

**Comment by tbonfort** [comment]
Hi @thomascoquet,
the problem here is that osio does request deduplication/mutualisation, which means that there may be multiple callers waiting on a single http request. The fact that the first caller cancels its request does not mean that the request should be cancelled for all other callers, which is not handled by your proposition. If you come up with a solution that handles this please go ahead and propose, but as it is this is not something we can go ahead with.

**Comment by thomascoquet** [comment]
@tbonfort indeed, forgot about that! However, I'd argue we have everything we need in osio to solve this, maybe at the price of slightly more complex synchronization.
On a more general level:
- do you agree with the approach (cancelling io)?
- have you in mind other options to cancel early godal calls that would suits better the lib philosophy? I don't mind doing some research work if needs be.

**Comment by tbonfort** [comment]
My feeling is that it is unfeasible to do this robustly without becoming overly complex:

- a godal.Warp() caller only knows the filename, and depending on the state of the lru cache there may be 0 to n requests actually going down to the http service. i.e. the caller does not know which blocks need to be locked/fetched
- a godal.Warp() on a vrt will result in gdal performing requests to the vrt's underlying rasterbands, which have a completely different keyname as the vrt itself
- even without the two previous issues, this would require adding an extra goroutine to each request in order to multiplex the context cancellations and actually close the http request only when all input contexts have been cancelled

**Comment by thomascoquet** [comment]
Had thought about point 3 as well, did not think about VRTs.
Ok, closing then!
